### ISSUE TITLE
Bug : CSS issue on landing page "Find your space" button

### ISSUE THREAD

**Issue by SaranshBangar** [The-MindSpace/MindSpace-Web#31]
**Describe the bug**
In the bottom half of the page, the main button is behaiving in a weird way, it keeps popping in and out

**Reproduce the bug**
1. Go to homepage
2. Go the bottom most section of homepage
3. Scroll down

**Expected Behavior**
It should just stay at its place instead of popping in and out

https://github.com/The-MindSpace/MindSpace-Web/assets/114401238/912fb335-9668-4375-b1df-2f5394fad9fb

**Comment by KanwalpreetSingh1823** [comment]
Hii @SaranshBangar  I'm Interested in fixing this issue. Please assign this issue to me.

**Comment by SaranshBangar** [comment]
@KanwalpreetSingh1823 I have already fixed it and raised a PR (#33)

**Comment by KanwalpreetSingh1823** [comment]
Okay

**Comment by Nitinshukla88** [comment]
Please assign this issue to me @TeeWrath

**Comment by SaranshBangar** [comment]
@Nitinshukla88 I have already fixed it and raised a PR (#33)

**Comment by Nitinshukla88** [comment]
Ok @SaranshBangar got it.
