### ISSUE TITLE
Favicon Icon

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [The-MindSpace/MindSpace-Web#46]
I would Like To Add A Favicon Icon For The MindSpace Webpage According Too The Project Theme

**Comment by Kapileswar-Moharana** [comment]
@TeeWrath Assign This Issue To Me Under SWOC

**Comment by TeeWrath** [comment]
@Kapileswar-Moharana I assign this issue to you. But you work only on this one.

**Comment by Kapileswar-Moharana** [comment]
@TeeWrath Sir Is There Any More Enhancement Need In The Favicon... Kindly Check It ...
