### ISSUE TITLE
Back To Top Button 

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [The-MindSpace/MindSpace-Web#48]
Adding Back To Top Button According To The Project Theme.

**Comment by Kapileswar-Moharana** [comment]
@TeeWrath Assign This Issue To Me Under SWOC

**Comment by krishnagitcontri** [comment]
Can I also work?

**Comment by MuskanKKW** [comment]
I have done this already in my portfolio website. 
You can check it out on this link: 
https://muskankkw.github.io/task2/
If you feel suitable, please assign this issue to me.

**Comment by Parmesh119** [comment]
Hello @TeeWrath, I hope you are fine.
Can you please assign this issue to me?

**Comment by TeeWrath** [comment]
@Kapileswar-Moharana I am assigning this to you

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I am assigning this to you

@TeeWrath Ok sir... I will complete it as soon as possible

**Comment by TeeWrath** [comment]
@Kapileswar-Moharana Make a detailed PR with link to the given issue so i can know which issue it is and enter in the scoresheet accordingly.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana Make a detailed PR with link to the given issue so i can know which issue it is and enter in the scoresheet accordingly.

Ok

**Comment by TeeWrath** [comment]
@Kapileswar-Moharana how long ?

**Comment by sherabhai** [comment]
@TeeWrath 

If you don't mind, assign this issue to me and will submit the PR today positively!

Best Regards,
**Shera Bhai**

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana how long ?

@TeeWrath  By Today evening I will open the PR

**Comment by Kapileswar-Moharana** [comment]
> @sherabhai I will assign this to you if @Kapileswar-Moharana fails to make a PR by tonight. This much delay is not expected at all from contributors.

Ok

**Comment by Kapileswar-Moharana** [comment]
> @sherabhai I will assign this to you if @Kapileswar-Moharana fails to make a PR by tonight. This much delay is not expected at all from contributors.

@TeeWrath Done You may Check It Now...
