### ISSUE TITLE
Adding Animation To All  Section In order to Details Visible

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [The-MindSpace/MindSpace-Web#49]
I would Like To Add Animation To All Of The Section Elements If Someone One Can Able to see Which Circle Is For What according To The Project Theme.

**Comment by Kapileswar-Moharana** [comment]
@TeeWrath Assign This Issue To Me Under SWOC

**Comment by pameladeysarkar2003** [comment]
please assign me with this issue @TeeWrath
