### ISSUE TITLE
Adding Hover To NavBar Section

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [The-MindSpace/MindSpace-Web#50]
I would Like To Add Hover To The NavBar Section

**Comment by Kapileswar-Moharana** [comment]
@TeeWrath Assign This Issue To Me Under SWOC

**Comment by Bharat-Deshpande** [comment]
i can fix this issue, please assign it to me. @TeeWrath

**Comment by ZubiyaAzeem** [comment]
hey, I would like to add a hover effect with some shadow effect, kindly assign this issue to me.

<img width="960" alt="Screenshot 2024-01-02 230726" src="https://github.com/The-MindSpace/MindSpace-Web/assets/146827791/9b156ace-5a11-4255-9544-69becf0e47e2">

**Comment by Komal-Rauniyar** [comment]
@TeeWrath
Hey....I can fix this issue...assign this issue with me under SWOC 2024

**Comment by Nitinshukla88** [comment]
Please assign this issue to me @TeeWrath

**Comment by pameladeysarkar2003** [comment]
I'm very much confident about fixing this issue,please assign me with issue @TeeWrath

**Comment by TanushreeBorase** [comment]
I would like to work on this issue @TeeWrath under SWOC'24.Please assign me this issue.
