### ISSUE TITLE
Smooth Scroll Effect

### ISSUE THREAD

**Issue by TeeWrath** [The-MindSpace/MindSpace-Web#6]
- [ ] Add Smooth Scroll Effect when surfing the website though navbar.

**Comment by TanyaSingh103** [comment]
Hi @TeeWrath ! I'm interested in working on this issue for SWOC24, kindly assign this to me :)

**Comment by Karnankita04** [comment]
Hi @TeeWrath ! please assign this issue to me.. I am interested.

**Comment by sambitsingha** [comment]
**Hey , with smooth scroll effect , I can do the scroll reveal effect too , which is each element is revealed on scrolled and then disappears thereafter.**

There are many customisations to this effect , like scroll reveal from top, bottom , left , right , then we can manilpulate the delay of each element to make it look more nice. 

### I would like to work on it.

**Comment by pankhuri92** [comment]
Hey @TeeWrath ! I wanna work on this. Please assign it to me.

**Comment by muskan42** [comment]
Hi @TeeWrath I am interested in solving the issue.

**Comment by royGarima1518** [comment]
@TeeWrath I'am interested in this issue. Please assign me

**Comment by Tuhin114** [comment]
Hi! @TeeWrath I have attached a video regarding your issue about smooth scrolling....if you like it...please assign me this  and let me create a pull request.....

https://github.com/The-MindSpace/MindSpace-Web/assets/132370086/fa8799e6-1474-433a-b8db-4d4c6bf95d51

**Comment by Mrpai2318** [comment]
@TeeWrath I am interested in this issue. Please assign me

**Comment by PRITISH212121** [comment]
i have worked with css animations and smooth scroll effect a lot,pleasse assign it to me

**Comment by Tymnspayce** [comment]
Just Fixed the Scroll Effect and many more things and raised the pull request.

![image](https://github.com/The-MindSpace/MindSpace-Web/assets/138722584/6780af9d-19e4-446e-826e-06c6ccd54f50)

https://github.com/The-MindSpace/MindSpace-Web/assets/138722584/79e7a692-dea4-4441-9a88-aee826bd101d

**Comment by Y-ash-h** [comment]
Hi @TeeWrath ! I'm interested in fixing this issue.
Please assign this issue to me.

**Comment by TeeWrath** [comment]
@Tuhin114 You can make a PR

**Comment by Tuhin114** [comment]
@TeeWrath Thank you for assigning me regarding this issue...I have already done my PR (#39) regarding this issue...
