### ISSUE TITLE
[SWOC'24] Changing color of About to Match UI

### ISSUE THREAD

**Issue by shivamm-verma** [The-MindSpace/MindSpace-Web#68]
# Perquisites

-  I am an Open Source Contributor.
- I follow the Contributing Guidelines.

# Description📃

to change color of About in footer to white, to match this in the UI.

# Screenshots📸

*Before*
![Screenshot before](https://github.com/The-MindSpace/MindSpace-Web/assets/98605616/3c5b7adc-e617-493d-b243-607d983739b1)

*After*
![Screenshot after](https://github.com/The-MindSpace/MindSpace-Web/assets/98605616/9a116b04-012c-4e4c-a11e-5441102f094c)

**Comment by shivamm-verma** [comment]
Please Assign this Issue to me, so that I can start working on it.
@TeeWrath  @bhaskar1001101

**Comment by diyaaa02** [comment]
Please assign me the issue .Looking forward to contribute @TeeWrath

**Comment by agastya3636** [comment]
please assign me the issue.Looking forward to contribute @TeeWrath

**Comment by pameladeysarkar2003** [comment]
please assign me this issue.Looking forward to contribute @TeeWrath

**Comment by ard0103** [comment]
@TeeWrath @agastya3636 kindly assign this issue to me

**Comment by VIDHISHAK15** [comment]
@agastya3636 @TeeWrath  can u please assign me this task under swoc
