### ISSUE TITLE
Footer extra margin

### ISSUE THREAD

**Issue by TeeWrath** [The-MindSpace/MindSpace-Web#81]
- [ ] Footer extra white margin below it has to be removed
![dikkatfuckl](https://github.com/The-MindSpace/MindSpace-Web/assets/117584718/cf2bbb98-ff88-4ca7-8fe3-ff1716ac677b)

**Comment by Hacxmr** [comment]
Hey! @TeeWrath  I am interested in resolving this issue.

**Comment by PranavSangave** [comment]
Hey! @TeeWrath I have just made one pull request after fixing this bug. It is my first contribution in this project.

**Comment by TeeWrath** [comment]
@PranavSangave okay.
