### ISSUE TITLE
Horishontal scrollbar in index page 

### ISSUE THREAD

**Issue by siddhant-2002** [The-MindSpace/MindSpace-Web#85]
in index page there is a horishontal scroll bar which is not looking good and its irritating too 
![mind space](https://github.com/The-MindSpace/MindSpace-Web/assets/112260375/0c080217-7698-4db1-81de-37e9e695200e)

**Comment by siddhant-2002** [comment]
@TeeWrath i will solve assign it to me

**Comment by pameladeysarkar2003** [comment]
@TeeWrath i will be grateful if you assign me with this issue

**Comment by Mohit5Upadhyay** [comment]
@TeeWrath can you it to me . I will surely fix the issue of horizontal scroll bar .
